<a href="https://colab.research.google.com/github/Jane-BA/PythonNotes-Colab/blob/main/Librerias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

Usa el objeto array para procesar matrices multidimencionales, es un contenedor rapido y flexible para ciencia de datos y finanzas.\
Esta diseñado especificamente para operaciones de arreglos por lo que la eficiencia de almacenamiento y el rendimiento de entrada y salida de arreglos son mucho mejores que las listas anidadas

In [ ]:
import  numpy as np

In [ ]:
'''Mismo tipo de datos'''
'''Mismo numero de elementos'''
miArray = np.array( [[0, 1, 2, 3], [4, 5, 6, 7]] )
print(miArray)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
miArray.shape # Tamaño del array (filas, columnas) // Cuantos hay?

(2, 4)

In [ ]:
miArray[1, 2] # Obteniendo 1 valor

6

In [ ]:
miArray[1] # Obteniendo una fila completa

array([4, 5, 6, 7])

In [ ]:
miArray[ :,2] # Obteniendo columna completa

array([2, 6])

# Random

In [ ]:
import random as r

In [ ]:
'Random solo da un numero aleatorio en decimal'
probabilidad = r.random()
probabilidad

0.18970868538586327

In [ ]:
'Randint genera aleatorio entre valore deseados'
dado = r.randint(1, 6)
dado

4

In [ ]:
import numpy as np

In [ ]:
# Crear una matriz con numeros aleatorios
'(aleatorios deseados (tamaño del arreglo))'
matriz = np.random.randint(150 ,200, (2, 3))
matriz

array([[160, 176, 152],
       [176, 181, 182]])


# **1.**  Yahoo Finance en linea


In [9]:
import numpy as np
import pandas as pd

!pip install yfinance #(instalar si no se tiene)
import yfinance as yf

# Habilita el override de Yahoo Finance en el módulo pandas_datareader.
from pandas_datareader import data as pdr

# Importa el módulo 'datetime' de la biblioteca estándar de Python para manejar fechas y horas.
from datetime import datetime

En programación y computación, "**override**" se refiere a reemplazar o modificar una funcionalidad existente.\
En el caso de `yf.pdr_override(),` se está modificando el comportamiento predeterminado del módulo `pandas_datareader` para que utilice Yahoo Finance como fuente de datos.

In [13]:
# Sobreescribe el metodo de descarga  de datos de Yahoo Finance en pandas_datareader
# para mejorar la compatibilidad y funcionalidad
yf.pdr_override()
# Define una lista de tickers que se utilizarán (Datos de las empresas)
listatickers = ['TSLA', 'AAPL', 'KO', 'MCD','NFLX','WMT','F','EBAY', 'AMZN','MSFT',]

In [14]:
# Define las variables 'inicio' y 'fin' con fechas específicas usando el módulo 'datetime'.
inicio = datetime(2018, 9, 26)
fin = datetime(2023, 9, 26)



> Utiliza la función `get_data_yahoo` del módulo `pdr` para obtener datos de los tickers especificados entre las fechas 'inicio' y 'fin'.



**Opcion 1**\
`datos = pdr.get_data_yahoo(listatickers, inicio, fin)`\
La variable 'datos', guarda la tabla

In [15]:
'Opcion 2'
matrizprecios = pd.DataFrame()
for t in listatickers:
  matrizprecios[t] = pdr.get_data_yahoo(t, inicio, fin)['Adj Close']

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed


In [16]:
matrizprecios

TSLA        AAPL         KO         MCD        NFLX  \
Date                                                                    
2018-09-26   20.638666   52.568001  38.606918  145.919434  377.880005   
2018-09-27   20.501333   53.648365  38.741646  146.597275  380.709991   
2018-09-28   17.651333   53.836773  38.893211  147.266281  374.130005   
2018-10-01   20.713333   54.199284  38.926895  146.720535  381.429993   
2018-10-02   20.068001   54.681030  39.162663  145.408844  377.140015   
...                ...         ...        ...         ...         ...   
2023-09-19  266.500000  178.364563  57.262371  274.909302  396.200012   
2023-09-20  262.589996  174.798676  57.518269  273.990051  386.299988   
2023-09-21  255.699997  173.244797  56.632465  268.079285  384.149994   
2023-09-22  244.880005  174.101410  56.691521  269.067719  379.809998   
2023-09-25  246.990005  175.386337  56.100983  266.656006  384.799988   

                  WMT          F       EBAY        AMZN        MSFT  
Date                                                                 
2018-09-26  28.759823   7.044074  30.766445   98.742500  107.570587  
2018-09-27  28.619959   7.013679  30.546547  100.649002  107.976410  
2018-09-28  28.553072   7.028875  30.253359  100.150002  107.938660  
2018-10-01  28.702047   7.082067  29.786089  100.218002  109.108925  
2018-10-02  28.930090   6.990881  29.831905   98.565498  108.674789  
...               ...        ...        ...         ...         ...  
2023-09-19  54.074314  11.897725  43.121166  137.630005  327.378906  
2023-09-20  54.249729  11.708269  43.190365  135.289993  319.529358  
2023-09-21  53.591091  11.556706  43.417736  129.330002  318.294159  
2023-09-22  53.733414  11.774578  42.636772  129.119995  315.783936  
2023-09-25  53.971710  11.916670  43.318878  131.270004  316.311890  

[1257 rows x 10 columns]

#**2.**  Codigo generado por ChatGPT

In [ ]:
# Importar librerias
import yfinance as yf
import pandas as pd
from pandas_datareader import data as pdr

In [ ]:
# Sobrescribir pandas_datareader con yfinance
yf.pdr_override()

In [17]:
# Lista de tickers de empresas de energias renobables
tickers = ['ENPH', 'RUN', 'FSLR', 'VWS.CO']

In [18]:
# Obtener datos
data = pdr.get_data_yahoo(tickers, start="2018-10-01", end="2023-10-01", interval="1mo")

[*********************100%%**********************]  4 of 4 completed


In [ ]:
# Filtrar solo los precios de cierre ajustados y eliminar las filas vacias
adj_close = data['Adj Close'].dropna()

In [21]:
# Reindexar las fechas en el formato 'Mes Año'
adj_close.index = adj_close.index.strftime('%B %Y')

In [22]:
# Exportar a Excel
adj_close.to_excel("Precios_Cierre_Ajustado_Energias_Renobables.xlsx")
print("Exportado con éxito.")

Exportado con éxito.


In [23]:
adj_close

Ticker                ENPH        FSLR        RUN      VWS.CO
Date                                                         
October 2018      4.540000   41.799999  12.260000   79.819328
November 2018     5.400000   44.450001  14.650000   95.064400
December 2018     4.730000   42.459999  10.890000   95.083725
January 2019      7.230000   50.590000  13.300000  103.952538
February 2019     9.070000   52.549999  15.510000  105.498306
March 2019        9.230000   52.840000  14.060000  108.203392
April 2019       10.040000   61.529999  15.210000  116.318642
May 2019         15.170000   58.040001  15.660000  107.225060
June 2019        18.230000   65.680000  18.760000  110.942711
July 2019        28.150000   64.489998  19.049999  108.555588
August 2019      29.670000   62.070000  15.330000   97.539581
September 2019   22.230000   58.009998  16.705000  104.055267
October 2019     19.430000   51.790001  15.540000  106.990257
November 2019    21.870001   55.240002  13.880000  126.282951
December 2019    26.129999   55.959999  13.810000  131.722473
January 2020     31.520000   49.580002  17.030001  131.644196
February 2020    48.970001   45.770000  19.340000  127.065620
March 2020       32.290001   36.060001  10.100000  108.125114
April 2020       46.830002   44.009998  14.030000  114.699501
May 2020         58.189999   46.619999  16.700001  135.607513
June 2020        47.570000   49.500000  19.719999  133.941666
July 2020        60.360001   59.549999  36.689999  160.991791
August 2020      77.230003   76.589996  56.555000  188.081543
September 2020   82.589996   66.199997  77.070000  204.264023
October 2020     98.089996   87.050003  52.020000  216.361206
November 2020   136.570007   93.430000  64.080002  252.950256
December 2020   175.470001   98.919998  69.379997  285.473846
January 2021    182.350006   99.150002  69.269997  264.551636
February 2021   176.059998   81.019997  62.580002  228.954178
March 2021      162.160004   87.300003  60.480000  258.205566
April 2021      139.250000   76.529999  49.000000  256.024139
May 2021        143.050003   76.110001  44.720001  236.397171
June 2021       183.630005   90.510002  55.779999  244.383560
July 2021       189.600006   86.040001  52.970001  230.806686
August 2021     173.729996   94.000000  44.250000  253.867401
September 2021  149.970001   95.459999  44.000000  257.061951
October 2021    231.630005  119.589996  57.680000  277.826538
November 2021   250.000000  103.599998  46.040001  219.625748
December 2021   182.940002   87.160004  34.299999  199.659760
January 2022    140.470001   78.379997  25.930000  176.648972
February 2022   166.699997   75.290001  27.280001  217.129990
March 2022      201.779999   83.739998  30.370001  199.410187
April 2022      161.399994   73.029999  19.980000  182.509003
May 2022        186.190002   70.610001  26.120001  177.059998
June 2022       195.240005   68.129997  23.360001  149.899994
July 2022       284.179993   99.169998  32.689999  189.539993
August 2022     286.440002  127.550003  33.029999  186.419998
September 2022  277.470001  132.270004  27.590000  141.619995
October 2022    307.000000  145.570007  22.510000  148.399994
November 2022   320.589996  172.529999  32.580002  179.460007
December 2022   264.959991  149.789993  24.020000  202.100006
January 2023    221.380005  177.600006  26.280001  198.779999
February 2023   210.529999  169.139999  24.040001  200.600006
March 2023      210.279999  217.500000  20.150000  199.000000
April 2023      164.199997  182.580002  21.040001  186.460007
May 2023        173.880005  202.960007  17.639999  198.339996
June 2023       167.479996  190.089996  17.860001  181.460007
July 2023       151.830002  207.399994  18.980000  181.639999
August 2023     126.529999  189.119995  15.630000  158.979996
September 2023  120.150002  161.589996  12.560000  151.559998

# **3.**  Importando datos CSV y agregando index

In [ ]:
import pandas as pd

# leer_csv(' direccion ', formato separador, columna de index )
aapl = pd.read_csv('C:/Users/USER/Downloads/AAPL.csv', sep = ',', index_col = 'Date')

# Otra forma de indicar cual es el index a una tabla
appl.set_index('Date')